export type ProjectType = "Raycast Extension" | "Discord Utility" | "Steam Tool" | "Automation" | "Web App" | "Python Utility" | "CLI Tool" | "Game Mod" | "Android App";

export interface Project {
    id: string;
    name: string;
    type: ProjectType;
    description: string;
    longDescription?: string;
    approach?: string;
    outcome?: string;
    techStack: string[];
    tags: string[];
    sourceUrl?: string;
    demoUrl?: string;
    purchaseUrl?: string;  // Gumroad etc.
    pageUrl?: string;      // Dedicated product page route
    featured: boolean;
    lumiApproved?: boolean; // Projects Lumi helped build/polish
}

export interface ActivityItem {
    id: string;
    type: "contribution" | "release" | "experiment";
    title: string;
    description: string;
    date: string; // ISO string or loose date "Dec 2025"
}

// BuildLogItem interface removed - Build Log section replaced with Quick Dev Stats

export const projects: Project[] = [
    {
        id: "meteor",
        name: "Meteor",
        type: "Android App",
        description: "Tasks and habits in one clean daily view. Local-first Android app with streaks, heatmaps, reminders, and a home screen widget.",
        longDescription: "Most habit apps treat tasks as an afterthought. Most task apps bolt on habits as recurring items. Meteor is built for both: a unified Today screen showing what you need to do and where your streaks stand, at a glance. Everything stays on your device — no account, no cloud, no ads.",
        approach: "Kotlin 2.x + Jetpack Compose with Material 3, two themes (Classic and Brutalist). Room for local persistence, DataStore for settings, WorkManager for streak rollover, Glance for the home screen widget, Play Billing 7.x for subscriptions.",
        outcome: "Freemium Android app on Google Play. Free tier: unlimited tasks + 3 habits. Pro: unlimited habits, full heatmap history, custom themes.",
        techStack: ["Kotlin", "Jetpack Compose", "Android", "Room", "Hilt"],
        tags: ["Android", "Productivity", "Habits", "Tasks", "Local-first"],
        pageUrl: "/meteor",
        featured: true,
        lumiApproved: true,
    },
    {
        id: "linux-sonar",
        name: "linux-sonar",
        type: "CLI Tool",
        description: "SteelSeries Sonar for Linux. Per-app audio routing, ChatMix, and mic effects on PipeWire.",
        longDescription: "Five virtual audio channels route apps independently to your headset. ChatMix slider balances game and chat volume, with hardware wheel support over USB-HID. Mic effects chain runs RNNoise, gate, 8-band EQ, compressor, and limiter as a PipeWire filter-chain subprocess. GTK4/libadwaita GUI with waybar integration.",
        approach: "Five libpipewire-module-filter-chain virtual sinks pinned to the headset via target.object. Per-app routing enforced by a daemon polling wpctl/pactl every 1.5s. WirePlumber persists moves across reboots. Mic chain runs as an isolated pipewire subprocess with debounced silent restarts.",
        outcome: "Full Sonar feature parity on Linux without SteelSeries software. Works on Arch with any PipeWire stereo output sink.",
        techStack: ["Python", "PipeWire", "WirePlumber", "GTK4", "libadwaita"],
        tags: ["Linux", "Audio", "PipeWire", "GTK4", "Open Source"],
        sourceUrl: "https://github.com/luinbytes/linux-sonar",
        pageUrl: "/linux-sonar",
        featured: true,
        lumiApproved: true,
    },
    {
        id: "file-deduplicator",
        name: "file-deduplicator",
        type: "CLI Tool",
        description: "The only CLI tool that finds similar images, not just exact duplicates. v3.0.0 released! 🚀",
        longDescription: "A fast, parallel CLI duplicate finder with a killer feature: perceptual image hashing. Finds similar photos even when they've been edited, compressed, or renamed — something no other CLI tool does.",
        approach: "Built in Go for speed with parallel SHA256 hashing. Implements dHash, aHash, and pHash algorithms for perceptual similarity detection. Cross-platform with safe defaults (dry-run, move-instead-of-delete).",
        outcome: "Open source with paid binaries. The only CLI tool with perceptual image deduplication — perfect for cleaning up massive photo libraries.",
        techStack: ["Go", "Perceptual Hashing", "CLI", "Cross-Platform"],
        tags: ["CLI", "Go", "Image Processing", "Open Source", "Released"],
        sourceUrl: "https://github.com/luinbytes/file-deduplicator",
        demoUrl: "https://luinbytes.github.io/file-deduplicator/",
        purchaseUrl: "https://luinbytes.gumroad.com/l/file-deduplicator",
        pageUrl: "/file-deduplicator",
        featured: true,
    },
    {
        id: "risk-of-anticheat",
        name: "Risk of Anticheat",
        type: "Game Mod",
        description: "BepInEx mod for Risk of Rain 2. ESP, legitbot, ragebot, projectile prediction, auto-pickup, and an 8-tab custom IMGUI menu.",
        longDescription: "Personal singleplayer/co-op replacement for the abandoned Aerolt mod. Five ESP providers render every chest, teleporter, enemy, pickup, and interactable without the NRE spam Aerolt became infamous for. Legitbot and Ragebot run peer-concurrently — legit steers the camera through a CollectLookInputInternal postfix, rage prefixes GenericSkill.ExecuteIfReady to redirect shots at resolved target time. Both share the same target selector, hitbox picker, and projectile-lead predictor backed by a tier-1 live-learning ProjectileSpeedTable.",
        approach: "BepInEx 5.4.21 + Harmony 2, hard-dep on RiskOfOptions for pause-menu integration. MMHOOK.RoR2-typed hooks layered on top of stock Harmony patches. Custom 860×560 IMGUI menu with 8 tabs (Rage, Legit, Players, World, Indicators, Misc, Spawner, Configs). Load-time VerifyPatches() enumerates every patched method so silent Harmony failures can't hide.",
        outcome: "~14k lines of C# across 57 source files. Auto-versioned MSBuild pipeline deploys directly into the active r2modman profile; Thunderstore-ready zip repackaged on every build.",
        techStack: ["C#", "BepInEx", "HarmonyX", "Unity IMGUI", "RiskOfOptions"],
        tags: ["Game Mod", "Risk of Rain 2", "Reverse Engineering", "C#", "BepInEx"],
        sourceUrl: "https://github.com/luinbytes/risk-of-anticheat",
        pageUrl: "/risk-of-anticheat",
        featured: true,
    },
    {
        id: "brc-trainer",
        name: "BrcTrainer",
        type: "Game Mod",
        description: "Internal trainer for Bomb Rush Cyberfunk. BepInEx 5 Mono plugin with an IMGUI sidebar — boost, speed, god mode, no heat, REP editor, time scale.",
        longDescription: "380px IMGUI sidebar with five tabs (Move, Health, Cops, Econ, World). Infinite Boost refunds boostCharge via UseBoostChargeForBoost postfix and a per-frame keepalive. No Heat pins WantedStars to 0 via postfix. God Mode and No Bail are prefixes on Player.GetHit and ChangeHP. Fly controller disables MovementMotor and drives Transform.position directly. REP editor writes StageProgress.reputation through SaveManager with a Shift-click ±1000 step.",
        approach: "BepInEx 5 Mono x64 + HarmonyLib targeting Reptile namespace types. Hooks resolve by reflection with cached MethodInfo so minor game updates don't require a rebuild. Proton-safe gamepad sampling — Input.GetKeyDown for joystick buttons misfires inside IMGUI's event loop, so GamepadNav samples in Update with cached last-state. Embedded TTFs (Doto, SpaceGrotesk, SpaceMono) extracted into the Windows/Wine system Fonts directory and registered via plain AddFontResourceW with a WM_FONTCHANGE broadcast — Font.CreateDynamicFontFromOSFont then resolves them. FR_PRIVATE doesn't work under Wine, so the install is process-wide.",
        outcome: "~3.3k lines of C# across 27 source files. Full L3+R3 gamepad open combo and D-pad navigation. VerifyPatches() enumerates every Reptile.* binding on boot so silent patch failures surface immediately.",
        techStack: ["C#", "BepInEx", "HarmonyLib", "Unity IMGUI", ".NET Standard 2.1"],
        tags: ["Game Mod", "Bomb Rush Cyberfunk", "Reverse Engineering", "C#", "BepInEx"],
        sourceUrl: "https://github.com/luinbytes/brc-trainer",
        pageUrl: "/brc-trainer",
        featured: true,
    },
    {
        id: "dagger-fall",
        name: "DaggerFall",
        type: "Game Mod",
        description: "External Linux trainer for Devil Daggers. Auto-bhop, full air control, Wayland overlay with dagger landing prediction, and sticky aim assist with lead prediction — all via process_vm_readv with no injection.",
        longDescription: "Pure external memory access via process_vm_readv/writev — no ptrace, no injection. Auto-bhop reads the grounded flag at 500Hz and fires a writev the frame it flips. Strafe mode writes velocity directly each tick with a 5-param air control model and configurable gravity reduction. The GTK3/Cairo click-through overlay (Wayland-compatible via gtk-layer-shell) reads the live dagger pool and projects floor intersections in real time accounting for gravity, speed, and player velocity inheritance. Aim assist estimates enemy velocity from delta-pos over 16ms ticks, leads the aim point forward, and uses sticky locking to avoid jitter. All struct offsets come from a plaintext config — not distributed.",
        approach: "Single-file C (GNU99) using Linux process_vm_readv/writev for zero-ptrace cross-process memory access. GTK3 + gtk-layer-shell for a Wayland compositor overlay with Cairo rendering. Xlib on an independent display connection for space-key polling without interfering with the GTK event loop. Pointer chain: global → arena → hero with null-check at each hop.",
        outcome: "~1.2k lines of C. Builds with a single gcc command. Runs externally alongside a live Devil Daggers session — no injection, no game modification.",
        techStack: ["C", "process_vm_readv", "GTK3", "Cairo", "gtk-layer-shell", "Xlib"],
        tags: ["Game Trainer", "Devil Daggers", "Linux", "Reverse Engineering", "C", "Wayland"],
        sourceUrl: "https://github.com/luinbytes/dagger-fall",
        pageUrl: "/dagger-fall",
        featured: true,
    },
    {
        id: "super-hacker-golf",
        name: "SuperHackerGolf",
        type: "Game Mod",
        description: "Client-side cheat mod for Super Battle Golf with aim assist, trajectory prediction, ESP, and client-side kick resistance.",
        longDescription: "MelonLoader mod that hooks Super Battle Golf through HarmonyX patches. Golf assist reads the game's own wind and terrain settings via reflection to predict exact ball trajectory, accounting for air damping, bounce chains, ground roll, and crosswind drift. Combat tools include a silent-aim weapon aimbot with legit/rage/custom modes, ESP overlay, force shield, item spawner, and bunnyhop. A client-side kick-resist layer keeps the session alive locally when the server decides you're out.",
        approach: "Built on MelonLoader 0.7.2 with HarmonyX runtime patching. Reverse-engineers ball physics from static analysis of GameAssembly.dll rather than guessed coefficients. CI pipeline compiles handwritten Unity type stubs so GitHub Actions builds without a game install. Reflection caches use cached FieldInfo and MethodInfo with fallback cascades for resilience across game updates.",
        outcome: "31 commits with auto-releasing tagged builds on every push to main.",
        techStack: ["C#", "MelonLoader", "HarmonyX", "Unity", ".NET 8"],
        tags: ["Game Mod", "Reverse Engineering", "C#", "Unity"],
        sourceUrl: "https://github.com/luinbytes/SuperHackerGolf",
        pageUrl: "/super-hacker-golf",
        featured: true,
    },
    {
        id: "wterm",
        name: "wterm",
        type: "CLI Tool",
        description: "A Warp-inspired terminal emulator. Fast, modern, AI-ready. Built with Go + Bubble Tea.",
        longDescription: "wterm is a modern terminal emulator inspired by Warp. Features a beautiful Tokyo Night theme, command block grouping, AI integration (BYOK), and persistent history. Single binary, zero dependencies.",
        approach: "Built with Go and the Bubble Tea TUI framework. Uses Lip Gloss for styling with a Tokyo Night-inspired color palette. PTY integration for real shell execution. NLP parser with 39 patterns for command understanding.",
        outcome: "In active development. Goal: feature parity with modern terminals like Warp, Alacritty, and Kitty. Focusing on AI integration and developer productivity.",
        techStack: ["Go", "Bubble Tea", "Lip Gloss", "PTY", "NLP"],
        tags: ["Terminal", "CLI", "Go", "TUI", "AI", "Developer Tools"],
        sourceUrl: "https://github.com/luinbytes/wterm",
        demoUrl: "https://luinbytes.github.io/wterm/",
        featured: true,
        lumiApproved: true,
    },
    {
        id: "devscribe",
        name: "DevScribe",
        type: "CLI Tool",
        description: "AI-powered terminal session logger — git log for your whole dev life. Silent background logging, AI summaries, fuzzy search.",
        longDescription: "DevScribe silently watches your terminal sessions and builds a searchable, AI-summarized log. Get plain-English summaries of what you built, broke, and learned — perfect for weekly standups, portfolio documentation, or just remembering what you did last Tuesday.",
        approach: "Uses shell hooks to capture every command with exit codes and timestamps. Auto-tags sessions with git repo names. Integrates LiteLLM for AI-powered 5-bullet session recaps. Built with Python 3.12+ for cross-platform compatibility across Linux, macOS, and Windows.",
        outcome: "Never lose context again. Search your entire command history, export markdown reports, and get instant AI summaries of your work sessions.",
        techStack: ["Python", "LiteLLM", "Shell Hooks", "CLI"],
        tags: ["CLI", "DevTools", "AI", "Productivity", "Python"],
        sourceUrl: "https://github.com/luinbytes/devscribe",
        demoUrl: "https://luinbytes.github.io/devscribe/",
        featured: true,
        lumiApproved: true,
    },
    {
        id: "bytebot",
        name: "ByteBot",
        type: "Discord Utility",
        description: "A powerful Discord bot with moderation, utilities, games, and BytePod voice channels.",
        longDescription: "ByteBot is a feature-rich Discord bot offering moderation tools, custom commands, F1 racing data, War Thunder stats, and unique BytePod system for dynamic voice channel management.",
        approach: "Built with Node.js and discord.js, featuring a modular command architecture, Drizzle ORM, and real-time API integrations.",
        outcome: "Streamlined server management with gaming integrations and an intuitive control system.",
        techStack: ["JavaScript", "Node.js", "Discord.js", "Drizzle ORM", "SQLite"],
        tags: ["Discord", "Bot", "Moderation", "F1", "Gaming"],
        sourceUrl: "https://github.com/luinbytes/bytebot-definitive-edition",
        featured: true,
        lumiApproved: true,
    },
    {
        id: "afk-tracker",
        name: "AFK Tracker",
        type: "Web App",
        description: "Smart AFK (Away From Keyboard) tracker with AI-powered estimations and analytics.",
        longDescription: "A feature-rich productivity tool that tracks your break times with AI-powered predictions, comprehensive analytics, achievements, and gamification to help you understand and optimize your work/break patterns.",
        approach: "Built with pure HTML/CSS/JavaScript (no frameworks), using IndexedDB for local storage and Canvas API for visualizations. Features fuzzy matching for grouping similar AFK reasons and statistical outlier detection for accurate predictions.",
        outcome: "100% privacy-focused with all data stored locally in the browser. Helps users optimize their productivity through data-driven insights about their break patterns.",
        techStack: ["JavaScript", "HTML5 Canvas", "IndexedDB", "Web Audio API", "Service Worker"],
        tags: ["Productivity", "Analytics", "AI", "PWA", "Privacy"],
        sourceUrl: "https://github.com/luinbytes/afk",
        demoUrl: "https://luinbytes.github.io/afk/",
        featured: true,
    },
    {
        id: "window-walker",
        name: "Window Walker",
        type: "Raycast Extension",
        description: "Quickly switch between windows and manage your workspace from Raycast.",
        longDescription: "A fast and intuitive window switcher for Raycast. Search and jump to any open window instantly with keyboard-first navigation.",
        approach: "Uses native system APIs to enumerate windows and provide instant switching with fuzzy search.",
        outcome: "Seamless window management without lifting your hands from keyboard.",
        techStack: ["TypeScript", "Raycast API"],
        tags: ["Productivity", "Windows", "Workspace"],
        sourceUrl: "https://github.com/luinbytes/extensions/tree/window-walker-extension",
        featured: true,
    },
    {
        id: "lifx-controller",
        name: "LIFX Controller",
        type: "Raycast Extension",
        description: "Control your LIFX smart lights directly from Raycast.",
        longDescription: "Full control over your LIFX smart lighting ecosystem. Toggle lights, adjust brightness, change colors, and manage scenes without leaving your keyboard.",
        approach: "Integrates with LIFX HTTP API for reliable cloud-based control with natural language commands.",
        outcome: "Instant smart home control from your launcher.",
        techStack: ["TypeScript", "Raycast API", "LIFX API"],
        tags: ["Smart Home", "LIFX", "Automation"],
        sourceUrl: "https://github.com/luinbytes/extensions/tree/lifx-controller-extension",
        featured: true,
    },
    {
        id: "bed-time-calculator",
        name: "Bed Time Calculator",
        type: "Raycast Extension",
        description: "Calculate optimal sleep and wake times based on 90-minute sleep cycles.",
        longDescription: "Plan your sleep schedule around natural 90-minute sleep cycles to wake up feeling refreshed. Calculate when to go to sleep, when to wake up, or both.",
        approach: "Uses sleep science to calculate optimal bedtimes or wake times based on cycle completion, helping you avoid waking up mid-cycle.",
        outcome: "Better mornings through cycle-aware sleep scheduling.",
        techStack: ["TypeScript", "Raycast API"],
        tags: ["Health", "Productivity", "Sleep"],
        sourceUrl: "https://www.raycast.com/khlebobul/bed-time-calculator",
        featured: true,
    },
    {
        id: "raycast-extensions",
        name: "Raycast Extensions",
        type: "Raycast Extension",
        description: "A collection of powerful extensions for Raycast to boost productivity.",
        longDescription: "I develop and maintain several extensions for Raycast store, focusing on system monitoring and developer tools.",
        approach: "Built using React, Node.js, and Raycast API. Optimized for speed and keyboard-first interactions.",
        outcome: "Used by thousands of developers to streamline their daily workflows.",
        techStack: ["TypeScript", "React", "Node.js"],
        tags: ["Raycast", "Productivity", "Open Source"],
        sourceUrl: "https://github.com/luinbytes/extensions",
        featured: false,
    },
    {
        id: "fastuploader",
        name: "FastUploader",
        type: "Automation",
        description: "Automates uploading files via shareX to a custom host.",
        longDescription: "Run a script to grab the most recent clip in your clips folder and upload it to your custom host using ShareX's API.",
        approach: "Simple and efficient automation.",
        outcome: "Automated file uploads to a custom host.",
        techStack: ["Python", "Automation"],
        tags: ["Bot", "Canvas", "Scripting"],
        sourceUrl: "https://github.com/luinbytes/fast_uploader",
        featured: false,
    },
    {
        id: "bongocat",
        name: "Bongo Cat",
        type: "Python Utility",
        description: "A Python project featuring the legendary Bongo Cat.",
        techStack: ["Python"],
        tags: ["Fun", "Python"],
        sourceUrl: "https://github.com/luinbytes/bongocat",
        featured: false,
    },
];

// buildLog export removed - Build Log section replaced with Quick Dev Stats in activity.tsx
